apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blackbox-exporter.config.name" . }}
  namespace: kube-system
  labels:
    app: prometheus
    role: monitoring
    resources.gardener.cloud/garbage-collectable-reference: "true"
immutable: true
data:
{{ include "blackbox-exporter.config.data" . | indent 2 }}
