global:
  vpaEnabled: false
kubernetes-dashboard:
  enabled: false
  images:
    kubernetes-dashboard: image-repository:image-tag
    kubernetes-dashboard-metrics-scraper: image-repository:image-tag
nginx-ingress:
  enabled: false
  images:
    nginx-ingress-controller: image-repository:image-tag
    ingress-default-backend: image-repository:image-tag
