apiVersion: {{ include "networkpolicyversion" . }}
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Alertmanager to be reached from the ingress.
  name: allow-alertmanager
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      component: alertmanager
      gardener.cloud/role: monitoring
      role: monitoring
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          role: garden
      podSelector:
        matchLabels:
          app: nginx-ingress
          component: controller
    - namespaceSelector:
        matchLabels:
          role: kube-system
      podSelector:
        matchLabels:
          app: nginx-ingress
          component: controller
  policyTypes:
  - Ingress
