---
apiVersion: v1
kind: Secret
metadata:
  name: internal-domain-example-com
  namespace: garden
  labels:
    gardener.cloud/role: internal-domain
  annotations:
    dns.gardener.cloud/provider: aws-route53
    dns.gardener.cloud/domain: example.com
  # dns.gardener.cloud/include-zones: "first-zone-id,second-zone-id"
  # dns.gardener.cloud/exclude-zones: "first-zone-id,second-zone-id"
type: Opaque
data: {}
  # Actual values here depend on the DNS extension of your choice.
  # For example, check out https://github.com/gardener/external-dns-management and find a lot of
  # example secret manifests here: https://github.com/gardener/external-dns-management/tree/master/examples
