{{ if .Values.targetKubeconfig }}
apiVersion: v1
kind: Secret
metadata:
  name: gardener-resource-manager-target-kubeconfig
  namespace: {{ .Release.Namespace }}
  labels:
    app: gardener
    role: resource-manager
type: Opaque
data:
  kubeconfig.yaml: {{ .Values.targetKubeconfig | b64enc }}
{{- end }}
