apiVersion: v1
kind: Service
metadata:
  name: gardener-resource-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: gardener
    role: resource-manager
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: {{ .Values.metricsPort }}
    protocol: TCP
  - name: health
    port: {{ .Values.healthPort }}
    protocol: TCP
  selector:
    app: gardener
    role: resource-manager
