---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-proxy.componentconfig.name" . }}
  namespace: kube-system
  labels:
    resources.gardener.cloud/garbage-collectable-reference: "true"
immutable: true
data:
{{ include "kube-proxy.componentconfig.data" . | indent 2 }}
