---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-proxy.conntrack-fix-script.name" . }}
  namespace: kube-system
  labels:
    app: kubernetes
    gardener.cloud/role: system-component
    origin: gardener
    role: proxy
    resources.gardener.cloud/garbage-collectable-reference: "true"
immutable: true
data:
{{ include "kube-proxy.conntrack-fix-script.data" . | indent 2 }}
