---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-proxy.secret-kubeconfig.name" . }}
  namespace: kube-system
  labels:
    resources.gardener.cloud/garbage-collectable-reference: "true"
immutable: true
type: Opaque
data:
{{ include "kube-proxy.secret-kubeconfig.data" . | indent 2 }}
