apiVersion: v1
kind: Service
metadata:
  name: apiserver-proxy
  namespace: kube-system
  labels:
    gardener.cloud/role: system-component
    origin: gardener
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: {{ .Values.adminPort }}
    protocol: TCP
  selector:
    app: kubernetes
    role: apiserver-proxy
