apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apiserver-proxy.config.name" . }}
  namespace: kube-system
  labels:
    gardener.cloud/role: system-component
    origin: gardener
    resources.gardener.cloud/garbage-collectable-reference: "true"
immutable: true
data:
{{ include "apiserver-proxy.config.data" . | indent 2 }}

