{{- if semverCompare ">= 1.22" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  annotations:
    ingressclass.kubernetes.io/is-default-class: true
  labels:
    origin: gardener
    gardener.cloud/role: optional-addon
    app: {{ template "nginx-ingress.name" . }}
    component: "{{ .Values.controller.name }}"
    release: {{ .Release.Name }}
  name: {{ .Values.controller.ingressClass }}
spec:
  controller: {{ include "nginx-ingress.class" . }}
{{- end }}