{{- if .Values.global.vpaEnabled }}
apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: addons-nginx-ingress-controller
  namespace: {{ .Release.Namespace }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      minAllowed:
        cpu: 100m
        memory: 128Mi
  targetRef:
    apiVersion: {{ include "deploymentversion" . }}
    kind: Deployment
    name: addons-nginx-ingress-controller
  updatePolicy:
    updateMode: "Auto"
{{- end }}
