apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-problem-detector
  labels:
    app.kubernetes.io/name: {{ include "node-problem-detector.name" . }}
    helm.sh/chart: {{ include "node-problem-detector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  namespace: kube-system
