{{- if .Values.global.vpaEnabled }}
apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: node-problem-detector
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: {{ include "daemonsetversion" . }}
    kind: DaemonSet
    name: node-problem-detector
  updatePolicy:
    updateMode: "Auto"
{{- end }}
