---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vpn-shoot.tls-auth.name" . }}
  namespace: kube-system
  labels:
    resources.gardener.cloud/garbage-collectable-reference: "true"
immutable: true
type: Opaque
data:
{{ include "vpn-shoot.tls-auth.data" . | indent 2 }}
