{{- if .Values.global.vpaEnabled }}
apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: vpn-shoot
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: {{ include "deploymentversion" . }}
    kind: Deployment
    name: vpn-shoot
  updatePolicy:
    updateMode: "Auto"
{{- end }}
