groups:
- name: kube-proxy.rules
  rules:
  - record: kubeproxy_network_latency:quantile
    expr: histogram_quantile(0.99, sum(rate(kubeproxy_network_programming_duration_seconds_bucket[10m])) by (le))
    labels:
      quantile: "0.99"
  - record: kubeproxy_network_latency:quantile
    expr: histogram_quantile(0.9, sum(rate(kubeproxy_network_programming_duration_seconds_bucket[10m])) by (le))
    labels:
      quantile: "0.9"
  - record: kubeproxy_network_latency:quantile
    expr: histogram_quantile(0.5, sum(rate(kubeproxy_network_programming_duration_seconds_bucket[10m])) by (le))
    labels:
      quantile: "0.5"
  - record: kubeproxy_sync_proxy:quantile
    expr: histogram_quantile(0.99, sum(rate(kubeproxy_sync_proxy_rules_duration_seconds_bucket[10m])) by (le))
    labels:
      quantile: "0.99"
  - record: kubeproxy_sync_proxy:quantile
    expr: histogram_quantile(0.9, sum(rate(kubeproxy_sync_proxy_rules_duration_seconds_bucket[10m])) by (le))
    labels:
      quantile: "0.9"
  - record: kubeproxy_sync_proxy:quantile
    expr: histogram_quantile(0.5, sum(rate(kubeproxy_sync_proxy_rules_duration_seconds_bucket[10m])) by (le))
    labels:
      quantile: "0.5"