images:
  alertmanager: image-repository:image-tag
  configmap-reloader: image-repository:image-tag

ingress:
  class: nginx
  hosts:
    - hostName: a.seed-1.example.com
      secretName: grafana-tls
  # admin : admin base64 encoded
  basicAuthSecret: YWRtaW46JGFwcjEkSWRSaVM5c3MkR3U1MHMxaGUwL2Z6Tzh2elE4S1BEMQ==

emailConfigs: []
replicas: 1
