apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.datasources.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: grafana
    role: {{ .Values.role }}
    resources.gardener.cloud/garbage-collectable-reference: "true"
immutable: true
data:
{{ include "grafana.datasources.data" . | indent 2 }}
