{{- define "grafana.deployment.annotations" -}}
reference.resources.gardener.cloud/configmap-{{ include "grafana.providers.name" . | sha256sum | trunc 8 }}: {{ include "grafana.providers.name" . }}
reference.resources.gardener.cloud/configmap-{{ include "grafana.datasources.name" . | sha256sum | trunc 8 }}: {{ include "grafana.datasources.name" . }}
reference.resources.gardener.cloud/configmap-{{ include "grafana.dashboards.name" . | sha256sum | trunc 8 }}: {{ include "grafana.dashboards.name" . }}
{{- end -}}
---
apiVersion: {{ include "deploymentversion" . }}
kind: Deployment
metadata:
  name: grafana-{{ .Values.role }}
  namespace: {{ .Release.Namespace }}
  labels:
    gardener.cloud/role: monitoring
    component: grafana
    role: {{ .Values.role }}
  annotations:
{{ include "grafana.deployment.annotations" . | indent 4 }}
spec:
  revisionHistoryLimit: 1
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      component: grafana
      role: {{ .Values.role }}
  template:
    metadata:
      annotations:
{{ include "grafana.deployment.annotations" . | indent 8 }}
      labels:
        gardener.cloud/role: monitoring
        garden.sapcloud.io/role: monitoring
        component: grafana
        networking.gardener.cloud/to-dns: allowed
        role: {{ .Values.role }}
        networking.gardener.cloud/to-loki: allowed
    spec:
      containers:
      - name: grafana
        image: {{ index .Values.images "grafana" }}
        imagePullPolicy: IfNotPresent
        env:
{{- if eq .Values.role "operators" }}
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "false"
        - name: GF_USERS_VIEWERS_CAN_EDIT
          value: "true"
{{- else }}
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "true"
{{- end }}
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_SNAPSHOTS_EXTERNAL_ENABLED
          value: "false"
        - name: GF_ALERTING_ENABLED
          value: "false"
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/grafana-storage
        - name: grafana-dashboards
          mountPath: /var/lib/grafana/dashboards
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboard-providers
          mountPath: /etc/grafana/provisioning/dashboards
        ports:
        - name: web
          containerPort: {{ required ".ports.grafana is required" .Values.ports.grafana }}
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 200m
            memory: 128Mi
      volumes:
      - name: grafana-storage
        emptyDir: {}
      - name: grafana-dashboards
        configMap:
          name: {{ include "grafana.dashboards.name" . }}
      - name: grafana-datasources
        configMap:
          name: {{ include "grafana.datasources.name" . }}
      - name: grafana-dashboard-providers
        configMap:
          name: {{ include "grafana.providers.name" . }}
