apiVersion: {{ include "rbacversion" . }}
kind: ClusterRole
metadata:
  name: gardener.cloud:psp:kube-system:apiserver-proxy
  labels:
    gardener.cloud/role: system-component
    origin: gardener
rules:
- apiGroups:
  - policy
  - extensions
  resourceNames:
  - gardener.kube-system.apiserver-proxy
  resources:
  - podsecuritypolicies
  verbs:
  - use
