# TODO(rfranzke): Delete this Helm chart in a future version.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: coredns
  annotations:
    resources.gardener.cloud/mode: Ignore
