# TODO(rfranzke): Delete this Helm chart in a future version.
---
apiVersion: {{ include "rbacversion" . }}
kind: ClusterRole
metadata:
  name: system:coredns
  annotations:
    resources.gardener.cloud/mode: Ignore
---
apiVersion: {{ include "rbacversion" . }}
kind: ClusterRoleBinding
metadata:
  name: system:coredns
  annotations:
    resources.gardener.cloud/mode: Ignore
