# TODO(rfranzke): Delete this Helm chart in a future version.
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: coredns
  namespace: {{ .Release.Namespace }}
  annotations:
    resources.gardener.cloud/mode: Ignore
