# TODO(rfranzke): Delete this Helm chart in a future version.
---
apiVersion: {{ include "deploymentversion" . }}
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
  annotations:
    resources.gardener.cloud/mode: Ignore
