kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  annotations:
    gardener.cloud/description: |
      Allows traffic to kubelet in TCP Port 10250
  name: gardener.cloud--allow-to-kubelet
  namespace: kube-system
  labels:
    origin: gardener
spec:
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-kubelet: allowed
  egress:
  - ports:
    - port: 10250
      protocol: TCP
  policyTypes:
  - Egress