apiVersion: {{ include "ingressversion" . }}
kind: Ingress
metadata:
  annotations:
{{- if semverCompare "< 1.22-0" .Capabilities.KubeVersion.GitVersion }}
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
{{- end }}
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: {{ .Chart.Name }}-basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
{{- if semverCompare ">= 1.22-0" .Capabilities.KubeVersion.GitVersion }}
  ingressClassName: {{ .Values.ingress.class }}
{{- end }}
  tls:
  {{- range .Values.ingress.hosts }}
  - secretName: {{ required ".secretName is required" .secretName }}
    hosts:
    - {{ required ".hostName is required" .hostName }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ required ".hostName is required" .hostName }}
    http:
      paths:
      - backend:
          {{- if semverCompare ">= 1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: prometheus-web
            port:
              number: 80
          {{- else }}
          serviceName: prometheus-web
          servicePort: 80
          {{- end }}
        path: /
        pathType: Prefix
  {{- end }}
