---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: {{ .Release.Namespace }}
data:
{{ range $name, $bytes := .Files.Glob "rules/**.yaml" }}
  {{ base $name }}: |-
{{ toString $bytes | indent 4}}
{{ end }}
# additional rules
{{- if .Values.additionalRules }}
{{toString .Values.additionalRules | indent 2}}
{{- end}}
# optional rules
{{- $files := .Files }}
{{- range $k, $v := .Values.rules.optional }}
{{- if and $v.enabled $v.rules }}
{{ ($files.Glob ( printf "optional-rules/%s.rules.yaml" $k)).AsConfig | indent 2 }}
{{- end }}
{{- end }}
